### ISSUE TITLE
影片心得回覆

### ISSUE THREAD

**Issue by azole** [ianhsu0116/hello-git#4]
如你的筆記所言，大腦是具有可塑性的，就像肌肉一樣，我們可以透過重訓來訓練肌肉成長，那也可以透過一些正確的方式來訓練我們的大腦，而且永遠不嫌晚。

然後，我也很喜歡數學喔，我比你幸運的是，我遇到的數學老師都很不錯，但沒有關係，未來是自學的年代，這個自學不見得是沒有老師的，我對自學的定義是，你要為自己訂下目標、找到合適的資源與方法，這個合適的資源包括書籍、包括老師教練、包括各種線上與實體的資源。

如果能為自己找到合適的方式，然後你也想要的話，成為資訊相關科系的研究生也是很有可能的，我自己雖然大學是資訊相關科系，但我研究所也是工作幾年後才回學校去念的，工作過後更清楚自己要什麼，也更知道適合自己與業界的學習方式，雖然職涯中斷了，但我覺得很值得呢。

**Comment by ianhsu0116** [comment]
我知道了，謝謝老師！
